[package]
name = "rs_lib"
version = "0.0.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.90"
serde = { version = "1.0.130", features = ["derive"] }
serde-wasm-bindgen = "0.4"
nom = "7.0.0"